### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by konioyxgq** [iamgroot42/A-LINK#7]
Can you provide a download address for a dataset? The official website is no longer able to register for download. Thank you

**Comment by iamgroot42** [comment]
Sure! The DFW dataset is available [here](http://iab-rubric.org/resources/dfw.html)

**Comment by konioyxgq** [comment]
Is DFW2018 and DFW2019 the same data set?

**Comment by konioyxgq** [comment]
The link you gave me seems to be the connection of DFW2018. Can you provide a link to DFW2019?

**Comment by iamgroot42** [comment]
It is not publicly available. You will have to contact the organizers to get access to the dataset.
