### ISSUE TITLE
Question about mask_matrix

### ISSUE THREAD

**Issue by IMCGU** [iamgroot42/A-LINK#8]
Hello,thanks for your great work about A-LINK!
I am not clear about part of the paper dfw2018.
 How to use the testing_data_mask_matrix.txt and make the dfw testing data according to 3 protocol?

thanks a lot!

**Comment by iamgroot42** [comment]
Hey, thanks for the comments! 😄 

You can download the dataset from [here](http://iab-rubric.org/resources/dfw.html), which should contain mask matrices for evaluating on test as well as train data. Then, using this mask matrix and your matrix of scores, you can compute metrics for a particular protocol as:

`python ROC_precompute.py <matrix_output_path> <output_fpr_tpr> <DFW_case>`

I was a bit lazy when writing this file 😅 so the mask matrix name is hard-coded into the code (see [here](https://github.com/iamgroot42/A-LINK/blob/master/utilities/ROC_precompute.py)). 

Hope this helps!

**Comment by IMCGU** [comment]
Thanks for your reply!
I will try it!
